update the project
Oscah01/todo-list-review pull request #1
Opened 2023-01-24 07:52 UTC by Oscah01

- add config files
 - add &remove functionality

2023-01-24 09:41 UTC, cindykandie requested changes
Please go over the reviews I made in your code below, they will guide you in applying the best javascript, CSS and HTML practices.

2023-01-24 09:41 UTC, cindykandie commented on README.md
> +
🌸 Kindly correctly edit your tech stack in the Readme by updating the section with only the technologies you used

2023-01-24 09:41 UTC, cindykandie commented on README.md
> +
🌸 For other viewers and visitors of your GitHub project, Be sure to add all the key features of your project

2023-01-24 09:41 UTC, cindykandie commented on README.md
> +
🌸 Kindly update the live link to your project to the correct link

2023-01-24 09:41 UTC, cindykandie commented on README.md
> +- [ ] **[]**
🌸 YANGNI Having blank brackets look bad you might not need this, consider only adding them when you need them

2023-01-24 09:41 UTC, cindykandie commented on src/CRUD.js
> +
🌸 On this file alone you have used the `window.()` more than three times, this may cause conflict on your window object when rendering the Javascript, kindly consider using just one window function to also avoid repetition(DRY)

2023-01-25 08:19 UTC, Oscah01 commented on src/CRUD.js
> +
Thank you @cindykandie I will try to fix this in the next project

2023-01-25 08:55 UTC, cindykandie approved these changes
Hi @Oscah01, 

# STATUS: APPROVED 😃 

![git-merge](https://user-images.githubusercontent.com/58642949/213831059-343282b2-1586-49bd-9df4-52bf6d64e5ef.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️  No linter errors 
✔️  Descriptive PR  
✔️  Good communication with code reviewer 💯 
✔️  Nice UI 💯 

## Optional suggestions
NO OPTIONAL SUGGESTIONS


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-01-25 09:57 UTC, merged